f = fopen(['jobs_' name], 'w') ;
fprintf(f,'getenv = true\n') ;
fprintf(f,'universe = vanilla\n') ;
fprintf(f,'executable = ./run_sims.sh\n');
fprintf(f,'output = ./log/$(Cluster).$(Process).out\n');
fprintf(f,'error = ./log/$(Cluster).$(Process).err\n');
fprintf(f,'log = ./log/$(Cluster).$(Process).log\n');
%fprintf(f,'requirements = (Machine =!= "node19.econets.org")\n') ;

format_s = 'arguments = "%d %s %d %d %d %g %d %g %g %g %g %g ' ; %landscape
format_s = [format_s, '%d %d %g %g '] ; %foodweb
format_s = [format_s, '%g %g %g '] ; % dispersal
format_s = [format_s, '%g %g %g %g %g %g %g %g %g %g '] ; %adaptation
format_s = [format_s, '%g ''%s'' '] ; %initial+replicates
format_s = [format_s, '''%s'' ''%s'' ''''''''%s$(Cluster).$(Process)''''''''"'] ; %tspan+name_prefix

landscape_seed_local = landscape_seed ;
foodweb_seed_local = foodweb_seed ;

for D0=logspace(log10(2e-8),-4,30)
for kappaW = logspace(-3,2,30)
%for D0=linspace(0, 3e-5,0)
%for kappaW = linspace(0,20,10)
    landscape_seed_local = landscape_seed_local + 1000 ;
    foodweb_seed_local = foodweb_seed_local + 1000 ;
    fprintf(f, format_s,...
    master_seed,...
    species_pool,... %boolean
    landscape_seed_local,...
    nsites,...
    edges,...
    excess,...
    centers,...
    p_exponent,...
    T_min,...
    T_max,...
    T_noise,...
    K_noise,... %factor
    foodweb_seed,...
    nspecies,...
    connectance,...
    competition,... %intra, for plants
    D0,...
    beta_mig,...
    gamma_0,...
    kappaR,...
    OmegaR,...
    Rmin,...
    x_cost_plants,...
    x_cost_animals,...
    priority,... %0: fear, 1:hunger
    kappaW,...
    OmegaW,...
    Wmin,...
    Wmax,...
    initial_B_cont,...
    replicates,...
    tspan_transient_pars,... %triples [first last qty]
    tspan_final_pars,....    %triples [first last qty]
    name_prefix...
    );
    fprintf(f,'\nqueue\n');

%format_s
%    sprintf('arguments = "%d %s %d', master_seed, 'test', 42)
%end
end
end
